apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    
    spec:
      containers:
        - name: auth-service
          image: gabrielmsosa/mscv-auth:v20
          ports:
            - containerPort: 8086
    

