 server:
  port: 8081  #port number
 
 eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}    
 
 spring:
  application:
    name: pandora-service  #service name
 
 logging:
  level:
    com.example.howtodoinjava: DEBUG
      
      