package com.pandoracenter.pandora.entity;

public enum EStatus {
  ACCEPT_FARMER,
  ACCEPT_FACTORY,
  REJECT_FARMER,
  REJECT_FACTORY,

}

 //IMPORTANTE!!! CARGAR LOS ROLES EN LA BASE DE DATOS

//flujos de estados: CAMINO FELIZ!!!
//ACCEPT_FACTORY_TRUCK_IN-->ACCEPT_FARMER_TRUCK_IN-->
//ACCEPT_FACTORY_WATER_DG-->ACCEPT_FARMER_WATER_DG-->
//ACCEPT_FACTORY_TRUCK_OUT-->ACCEPT_FARMER_TRUCK_OUT-->ACCEPT_FARMER_FACTORY(ESTADO FINAL)

//IMPORTANTE!!! CAMINO NO FELIZ:

//ACCEPT_FACTORY_TRUCK_IN-->REJECT_FARMER_TRUCK_IN-->ACCEPT_FARMER_TRUCK_IN-->(ABORT_FARMER)-->
//ACCEPT_FACTORY_WATER_DG-->REJECT_FARMER_WATER_DG-->ACCEPT_FARMER_WATER_DG-->(ABORT_FARMER)-->
//ACCEPT_FACTORY_TRUCK_OUT-->REJECT_FARMER_TRUCK_OUT-->ACCEPT_FARMER_TRUCK_OUT-->(ABORT_FARMER)-->ACCEPT_FARMER_FACTORY(ESTADO FINAL)
