apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory-service
  template:
    metadata:
      labels:
        app: factory-service
    
    spec:
      containers:
        - name: factory-service
          image: gabrielmsosa/msvc-factory:v5
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: factory-service
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    app: factory-service
    

