## YAML Template.
---
#spring:
#  application:
    #name: farmer-service
#server:
#  port: 8087
#eureka:
 # client:
 #   serviceUrl:
 #     defaultZone: http://localhost:8673/eureka
      
      
      

 server:
  port: 8087  #port number
 
 eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
      #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
 
 spring:
  application:
    name: farmer-service  #service name
 
 logging:
  level:
    com.example.howtodoinjava: DEBUG
      
 