## YAML Template.
---
spring:
  application:
  name: farmer-service
server:
  port: 8087


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
 