## YAML Template.
---
spring:
  application:
  name: msvc-frontend
server:
  port: 8073
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/