version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  #  image: confluentinc/cp-zookeeper:latest
    ports:
    - "2181:2181"
    networks:
      - "minet"
  kafka0:
    image: wurstmeister/kafka
#    image: confluentinc/cp-kafka:latest
    ports:
    - "9092:9092"
    environment:
   #   KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://kafka0:9092,LISTENER_ALICE://kafka0:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB   
      #    KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXTKAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      #KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    networks:
      - "minet"
#  auth-microservice:
 #   image: auth
  #  container_name: auth
   # environment:
    #  SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092 #esto es lo mas immportante con esto es que funciona

    depends_on:
     - zookeeper

          
    #networks:
     # - minet  
    
networks:
  minet:
    name: minet
    external: true
