package com.pandoracheckout.checkout.entity;

public enum StatusOut {
    ACCEPT_FARMER,
    ACCEPT_FACTORY,
    REJECT_FARMER,
    REJECT_FACTORY,
    AUDIT,

    ACCEPT_FACTORY_TRUCK_OUT,
    REJECT_FACTORY_TRUCK_OUT,
    REJECT_FARMER_TRUCK_OUT,
    ACCEPT_FARMER_TRUCK_OUT,

    ACCEPT_CHECKOUT

}
